Repository OriginTrail/neuroweb, pull requests merged in 2024-09, with the labels that each got.

#104 Add metadata-hash feature to Cargo.toml
  Cargo.lock
  runtime/Cargo.toml
  runtime/src/lib.rs
Labels: enhancement

#103 Bugfix/gas limit estimation
  README.md
  runtime/src/lib.rs
Labels: bug

#106 Testnet Runtime Upgrade v136
  Cargo.lock
  README.md
  node/Cargo.toml
  runtime/Cargo.toml
  runtime/src/lib.rs
Labels: release
